# Generated by Django 4.0.6 on 2024-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='qtd_votos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de votos'),
        ),
    ]
