# Generated by Django 4.0.6 on 2024-08-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('ano', models.IntegerField(verbose_name='Data de Publicação')),
                ('foto_capa', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('ano', models.IntegerField(verbose_name='Data de Publicação')),
                ('foto_capa', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
